### ISSUE TITLE
Cannot create service connection

### ISSUE THREAD

**Issue by elGonzass** [OutSystems/vsts#10]
Outsystems Platform **Version**:  10.0.828.0
Outsystems Integration (VSTS extension) **Version**: 1.0.50
Are **OutSystems** platform __logs__ supplied?: N
Are **VSTS/TFS** __logs__ in debug mode supplied?: N
Are **screenshots** supplied?: N
Steps to Reproduce: Create a service connection

Trying to create a service connection i get an error saying "The format of value {my service account key} is invalid.."

Thanks!

**Comment by falebarros** [comment]
Hi elGonzass,

Did you added "Bearer " before the "Authentication Token" you got from OutSystems LifeTime? (There is a space after the word "Bearer").

The field "Personal access token" is handled by VSTS. So we cannot add the "word" if there is not.

Thanks
Antonio

**Comment by elGonzass** [comment]
Thanks Antonio, i figured that one out yesterday. It'd be good to add to the documentation.

**Comment by falebarros** [comment]
Will do ASAP.
