### ISSUE TITLE
Provided module versions for creating version for the application with key '7cfaa243-c522-42d8-8a6e-df0fff265fd2' do not correspond to the current state of the application in environment with key 'aeeb3caf-c110-4f82-8202-893e865cb7dc'

### ISSUE THREAD

**Issue by sumo300** [OutSystems/vsts#12]
Outsystems Platform 10.0.828.0
Outsystems Integration (VSTS extension) 2.1.17
Are **OutSystems** platform __logs__ supplied?: N
Are **VSTS/TFS** __logs__ in debug mode supplied?: Y
Are **screenshots** supplied?: Y
Steps to Reproduce:
1. Try to deploy a single application from one environment to the next

Error Messages
`Provided module versions for creating version for the application with key '7cfaa243-c522-42d8-8a6e-df0fff265fd2' do not correspond to the current state of the application in environment with key 'aeeb3caf-c110-4f82-8202-893e865cb7dc'`

[tasklog_2.log](https://github.com/OutSystems/vsts/files/2398444/tasklog_2.log)
![2018-09-19_15-11-11](https://user-images.githubusercontent.com/5069447/45775640-612a4100-bc1e-11e8-9368-9c9df26d520b.png)

**Comment by falebarros** [comment]
Hi Michael,

Again, I kindly request that you uninstall and install again the Extension.
I just created a new version of the task: 2.1.18.
The Extension version should now start at 2.0.xx.

Thanks
Antonio

**Comment by sumo300** [comment]
I've verified that 2.0.5 of the extension is installed.  I just ran it again and it now shows 2.1.18 in the log.  This time it worked.

![outsytems-2 0 5](https://user-images.githubusercontent.com/5069447/46631923-e070ad80-cb16-11e8-9533-5a540a6cc9b4.PNG)
