### ISSUE TITLE
Feature - Add TFS Source code integration into Service Studio & Integration Studio applications.

### ISSUE THREAD

**Issue by thekingofspain** [OutSystems/vsts#3]
Service Studio is nice platform that handle low code management and CICD automatically.  For OutSystems to fully leverage the feature of TFS, there needs to be a check in extension that allows TFS work items to be tracked against a set of source and its related build.  Not every compile in Service Studio should be designated as a TFS build,  The TFS CICD builds should trigger upon as  Service Studio code checkin.

**Comment by joalmeid** [comment]
@thekingofspain ,

You're totally correct. The next phases would include work planning integration, source control integration and CD capabilities triggered by Outsystems Platform itself. Outsystems is evaluating all that for future developments.  We're updating the roadmap, so take a look at [Extension Roadmap](https://github.com/OutSystems/vsts/wiki/Extension-roadmap). Keep those suggestions coming!
