### ISSUE TITLE
##[error] Cannot read property 'Errors' of undefined

### ISSUE THREAD

**Issue by poliveira81** [OutSystems/vsts#4]
Hi,

I tagged my version in Lifetime.
I Created a "new release" and got this result:
![2017-11-09_0952-1](https://user-images.githubusercontent.com/20322186/32599316-0f583cba-c534-11e7-9bf8-aabb47e824cd.png)

In Lifetime, the result was this:
![2017-11-09_0952](https://user-images.githubusercontent.com/20322186/32599307-0b17acb2-c534-11e7-9cee-0ba57093d45e.png)

Here are the logs:
[ReleaseLogs_8.zip](https://github.com/OutSystems/vsts/files/1457158/ReleaseLogs_8.zip)

The release definition was:
![2017-11-09_0957](https://user-images.githubusercontent.com/20322186/32599419-6697b5b4-c534-11e7-9369-e0d4fd51c5f2.png)

**Comment by joalmeid** [comment]
Hi @poliveira81, 
*Please execute the Outsystems task with the **"system.debug"** variable in VSTS set to true, and send us the verbose logs.*
Also, take a look at [Submitting Bugs and Suggestions](https://github.com/OutSystems/vsts/wiki/Submitting-Bugs-and-Suggestions) for additional guidance.
Annnnd, you can reach the team at [Gitter](https://gitter.im/OutSystems/vsts).

**Comment by poliveira81** [comment]
Thanks for looking into it!

Please find verbose logs attached.
[ReleaseLogs_12.zip](https://github.com/OutSystems/vsts/files/1478910/ReleaseLogs_12.zip)

**Comment by joalmeid** [comment]
The logs you sent are **not** in verbose.
Go to the Release Definition, edit it, and create a new variable:
![image](https://user-images.githubusercontent.com/4800035/32910668-c9151894-cb01-11e7-9866-533d03a6aae7.png)

In the logs, you should see much more info and the variable registered i the initialization Job phase:
				[SYSTEM_DEBUG] --> [true]

**Comment by joalmeid** [comment]
Thanks, for the logs

This is the area of error: 
2017-11-16T14:28:49.8913830Z ##[debug]{}
2017-11-16T14:28:49.8913830Z ##[debug]task result: Failed
2017-11-16T14:28:49.9003864Z ##[error] Cannot read property 'Errors' of undefined
2017-11-16T14:28:49.9003864Z ##[debug]Processed: ##vso[task.issue type=error;] Cannot read property 'Errors' of undefined
2017-11-16T14:28:49.9033863Z ##[debug]Processed: ##vso[task.complete result=Failed;] Cannot read property 'Errors' of undefined
2017-11-16T14:28:49.9143883Z ##[section]Finishing: Deploy Field Services

Let me try to reproduce, and I'll come back to you.

**Comment by joalmeid** [comment]
The error occurred while executing the command 'Start' on the deployment plan previously created.

You should then have a similar message:
##[debug]deployCommandMessage = Command 'start' executed successfully for deployment 'd8f64fa6-f524-440c-a863-b0ee09bae9f0' .

Now, you could try executing the same exact release on Lifetime, and check the outcome. **Send screenshot**.

For example, in Lifetime, when you define a deployment plan, you can validate it. The OS Lifetime Rest API, still doesn't have that feature. You have to create a deployment plan that will be able to execute (no dependencies issues, etc...).

**Comment by poliveira81** [comment]
Hi João,

In this case there was no validation issue and I'm guessing the "Errors" which could not be read are related to the warnings that occurred during the deployment.

Below you can find the screenshot of the deployment logs on the Lifetime side for the exact same deployment plan.
![fireshot capture 5 - deployment to production_ - https___pvodemos outsystemscloud co](https://user-images.githubusercontent.com/20322186/32944988-9b5f6ee4-cb89-11e7-910b-fce25889e974.png)

**Comment by joalmeid** [comment]
@poliveira81 , *let's chat over gitter.*

The request for the Lifetime API to start, must have answered with some kind of error/msg.
The deployment plan execution did not start, or else you would see all the log, similar to the screenshot you sent.

Let's start with the basics: What's the version of OS and OS lifetime?

With the execution you're showing in screenshot, there are warnings, and those will happen the same way, when called from VSTS extension.

**Comment by poliveira81** [comment]
Here's an update batch of Logs for your reviewing pleasure :-)
[ReleaseLogs_15.zip](https://github.com/OutSystems/vsts/files/1491103/ReleaseLogs_15.zip)
![vstsuseractivity](https://user-images.githubusercontent.com/20322186/33069834-b3e64948-cead-11e7-8522-845b6398a131.png)
![vsts lifetime deployment](https://user-images.githubusercontent.com/20322186/33069856-cfb7564e-cead-11e7-8ce1-08f3d216a24b.png)

**Comment by joalmeid** [comment]
@poliveira81, sent you message over gitter. You have instructions to collect additional data.
Basically, it's a direct call to the Lifetime Deployments Start Command.
