### ISSUE TITLE
##[error] [400] Command 'start' can't be executed for deployment 'aa14bc97-e5a7-4a59-bfb7-ac3bfa30d045'.

### ISSUE THREAD

**Issue by poliveira81** [OutSystems/vsts#5]
Hi,

I was trying to deploy an invalid App (has missing references).
I get an error regarding "unable to execute" but the error should be "cannot create deployment plan because..."
![2017-11-09_1010](https://user-images.githubusercontent.com/20322186/32600070-4956f94a-c536-11e7-923c-ea1f954333c6.png)

The release is:
![2017-11-09_1011](https://user-images.githubusercontent.com/20322186/32600112-647e4dd6-c536-11e7-9b5e-4368cc4a0707.png)

Logs are:
[ReleaseLogs_9.zip](https://github.com/OutSystems/vsts/files/1457211/ReleaseLogs_9.zip)

**Comment by joalmeid** [comment]
Thanks @poliveira81 ! Indeed. The validation phase is not yet exposed by the OS Lifetime Rest API. We've decided to label this requests/issues as  **'Llifetime REST Api Debt'**. The goal is to make Outsystems team aware and prioritize within their product group.
