### ISSUE TITLE
Open in Browser - When I Click on Publish Icon

### ISSUE THREAD

**Issue by smkarnan** [OutSystems/vsts#6]
Outsystems Platform **Version**:
Outsystems Integration (VSTS extension) **Version**:
Are **OutSystems** platform __logs__ supplied?: N
Are **VSTS/TFS** __logs__ in d
[Bug-Screenshot.docx](https://github.com/OutSystems/vsts/files/1494899/Bug-Screenshot.docx)
ebug mode supplied?: Y
Are **screenshots** supplied?: Y
Steps to Reproduce:
1.Publish application and it should abort due to dependency
2.Click the close button at the bottom from the Error window.
3.Now click on the Publish Icon from the top.
4.It's open a application in browser instead of Publish the application.

Error Messages
No error Message, it's just a behavior issue.

**Comment by joalmeid** [comment]
Thanks @smkarnan, This issue you reported is specific to Outsystems Platform, and not Outsystems Integration (VSTS) extension.
I'll make this aware to Outsystems team.
