### ISSUE TITLE
Provided module versions for creating version for the application ... do not correspond to the current state of the application in environment

### ISSUE THREAD

**Issue by sumo300** [OutSystems/vsts#8]
TFS Version: 2017 Update 2
Outsystems Platform 10.0.710.0:
Outsystems Integration (VSTS extension) 1.0.42:
Are **OutSystems** platform __logs__ supplied?: Y
Are **VSTS/TFS** __logs__ in debug mode supplied?: Y
Are **screenshots** supplied?: Y

Steps to Reproduce:

1, Set up a simple Release definition using the OutSystems deployment task (see screenshot)
2. Run the deployment

Error Messages

[400] Provided module versions for creating version for the application with key '7cfaa243-c522-42d8-8a6e-df0fff265fd2' do not correspond to the current state of the application in environment 
with key 'aeeb3caf-c110-4f82-8202-893e865cb7dc'.

[tasklog_3.log](https://github.com/OutSystems/vsts/files/2014443/tasklog_3.log)

![outsystems-release-config](https://user-images.githubusercontent.com/5069447/40198409-6062e890-59e4-11e8-8e5f-2d294fac4c96.png)

[LT_ErrorLog.xlsx](https://github.com/OutSystems/vsts/files/2014451/LT_ErrorLog.xlsx)

**Comment by sumo300** [comment]
Note that the OutSystems service connection was tested and reported Success.  This tells me the API is working and the service key we generated in Lifetime is also correct.

**Comment by sumo300** [comment]
Note that we just upgraded to TFS 2018 Update 2 and the same errors still occur.

**Comment by sumo300** [comment]
Any chance anyone is going to look at this?  We were excited to be able to orchestrate OutSystems deployments from TFS and really need it for compliance reasons.  Originally, we thought this was written by the OutSystems team, but their support said it wasn't.  Any help is appreciated.

**Comment by falebarros** [comment]
Hi Mike,

Thanks for your persistence on this component and for your (hopefully still) excitement.
This issue reached OutSystems Product Management and I'm responsible for this component.
Please accept my and OutSystems apologies for our answer is way behind your expectations.

Our teams will look into what you have presented and I'll give you feedback no later than Monday afternoon. Ok?

Thanks
Antonio Barros

**Comment by sumo300** [comment]
Thanks!

> Our teams will look into what you have presented and I'll give you feedback no later than Monday afternoon. Ok?

**Comment by falebarros** [comment]
Hi Michael,

Our teams evaluated the logs. It is an internal OutSystems message.
We have to check the API code to understand the scenario that causes that message to be sent.

I'll get bat to you no later than Wednesday.
Thank you for the understanding.

Cheers
Antonio

**Comment by falebarros** [comment]
Hi Michael,

It looks the VSTS component did not implement the correct sequence of steps for the situation presented in your log.
We will have technical teams to design a solution. Then I will know when a fix will be available.

I´ll keep you informed.

Cheers
Antonio

**Comment by falebarros** [comment]
Hi Michael,

We are doing major refactoring on the component as we identified one use case was not implemented. Sorry. By the end of this week it will be available.

Thanks for the understanding.
Cheers
Antonio

**Comment by sumo300** [comment]
Thank you @falebarros

**Comment by sumo300** [comment]
@falebarros So where are we with this?

**Comment by sumo300** [comment]
@falebarros On June 19th, you said something would be available by the end of the week.  It's now end of August.  Is there any ETA on a fix for this extension?

**Comment by falebarros** [comment]
Hi Michael,

I'm really sorry with my answer to this issue. I know we did some changes but I guess they never got published.
Let me collect status and get back to you still this week.

Sorry again.
António

**Comment by ameyvaert** [comment]
I'm having the same issue right now.

2018-09-04T14:22:10.2732283Z ##[error] [400] Provided module versions for creating version for the application with key '[some key]' do not correspond to the current state of the application in environment with key '[some key]'.

**Comment by falebarros** [comment]
Hi,

I just have the confirmation, we will be launching the fix next week (scheduled for Monday).
It is under final tests...

Thank you for your patience.

Best regards
Antonio

**Comment by falebarros** [comment]
Hi,

Just released new version of VSTS component.

Thanks
Antonio

**Comment by sumo300** [comment]
@falebarros Thanks and we've updated.  However, now we are getting the following error which seems like the same error we were getting when trying to deploy after an OS 9 to OS 10 upgrade.

```
2018-09-14T14:06:55.3514880Z ##[error] [400] Provided module versions for creating version for the application with key '7cfaa243-c522-42d8-8a6e-df0fff265fd2' do not correspond to the current state of the application in environment with key 'aeeb3caf-c110-4f82-8202-893e865cb7dc'.
```

Should I open this as a new issue?

**Comment by falebarros** [comment]
Hi Michael,

In another issue I requested for you to uninstall and install VSTS Extension again (because I didn't find a way to refresh the extension; do you know a way to just refresh the extension?).
The Extension Version in the Marketplace is now 2.0.5. This version should have the error solved.

May you check please?

Thank you.
Antonio

**Comment by sumo300** [comment]
This is now working.  I was able to verify what you expect to be both the extension version and the task version.
