### ISSUE TITLE
Not able to connect with OutSystems Cloud instance

### ISSUE THREAD

**Issue by ameyvaert** [OutSystems/vsts#9]
At the moment we are trying to use the extension to connect VSTS to our OutSystems instance. Our OutSystems instance is not hosted on Azure but directly in the Outsystems cloud. Is it possible to use this extension with this setup? 

Currently I'm getting the following error when setting up the Service Connection in VSTS:

Failed to query service connection API: https://[our OutSystems instance] .outsystemsenterprise.com/lifetimeapi/rest/v1/applications. Error Message: The format of value '[our token]' is invalid.. 
Note: Verification may fail if the URL is not accessible from Visual Studio Team Services. However, it might still be valid and accessible from the agent that executes the build or release.

**Comment by ameyvaert** [comment]
Found the solution: 
Don't forget to add Bearer in front of the API token when creating the service connection in VSTS.

**Comment by falebarros** [comment]
Hi,

Thanks for sharing.

Best regards
Antonio
